name: Test and Lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9, '3.10']
        tox: [django, flake, codecov]
        exclude:
        - python: 3.8
          tox: flake
        - python: 3.8
          tox: codecov
        - python: 3.9
          tox: flake
        - python: 3.9
          tox: codecov
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      env:
        CODECOV_TOKEN: ${{ secrets.codecov_token }}
      run: |
        tox -e ${{ matrix.tox }}
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: simhnna
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: simhnna/silverstrike:dev

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

